### ISSUE TITLE
Add a set proxy script

### ISSUE THREAD

**Issue by paule96** [codez-one/CZ.PowerShell.NetworkTools#7]
Add a script to configure proxies for many tools like:

- powershell
- pwsh
- git
- npm
- docker
- apt-get
- ~~winget~~ (winget currentyl doesn't support a proxy)

and so on

**Comment by paule96** [comment]
the current work can be followed in the branch: [paule96/add_set_proxy_configuration](https://github.com/codez-one/CZ.PowerShell.NetworkTools/tree/paule96/add_set_proxy_configuration)

**Comment by DanielHabenicht** [comment]
Here are my scripts: 
```ps
$server_adress = "http://proxy.example.de:8080"

# Windows Proxy
echo " - Set IE Proxy"
set-itemproperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' "ProxyEnable" -value 1
set-itemproperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' "ProxyServer" -value $server_adress

# NPM Proxy
echo " - Set NPM Proxy"
npm config set proxy $server_adress
npm config set https-proxy $server_adress
npm set strict-ssl false
npm config get proxy

# Git Proxy
echo " - Set Git Proxy"
git config --global http.proxy $server_adress
git config --global https.proxy $server_adress
git config http.sslVerify false
git config --get http.proxy

# System
echo " - Set System Variables"
[Environment]::SetEnvironmentVariable("HTTP_PROXY", $server_adress, [EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("HTTPS_PROXY", $server_adress, [EnvironmentVariableTarget]::Machine)

```

```ps
# Windows Proxy
echo " - Set IE Proxy"
set-itemproperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" "ProxyEnable" -value 0  

# NPM Proxy
echo " - Set NPM Proxy"
npm config rm proxy
npm config rm https-proxy
npm set strict-ssl true
npm config get proxy

# Git Proxy
echo " - Set Git Proxy"
git config --global --unset http.proxy
git config --global --unset https.proxy
git config http.sslVerify true

# System
echo " - Set System Variables"
[Environment]::SetEnvironmentVariable("HTTP_PROXY", "", [EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("HTTPS_PROXY", "", [EnvironmentVariableTarget]::Machine)

```

**Comment by paule96** [comment]
npm 6.10.3 is speciell :D

**Comment by paule96** [comment]
Current Progress: All tools above can be configured with the scipt [here](https://github.com/codez-one/CZ.PowerShell.NetworkTools/blob/paule96/add_set_proxy_configuration/src/Set-ProxyConfigurtion.ps1)

to load the script in your current shell run `. ./src/Set-ProxyConfigurtion.ps1`.

Then you can call the main function with `Set-ProxyConfiguration -ConfigPath ./samples/basic.proxy.config.json`.
The path for the parameter configPath must point to a configuration file. Samples for them could be found [here](https://github.com/codez-one/CZ.PowerShell.NetworkTools/blob/paule96/add_set_proxy_configuration/samples/).

If you don't have admin / root rights run the function with the parameter `NoRoot` else you get error messages

**Comment by DanielHabenicht** [comment]
How far are you? 
Seems like you also set the proxy in wsl2? 

I can write some documentation and you can get it merged. I am feeling the pain again :D

Just some reminders for me:
https://www.techlear.com/blog/2021/03/08/how-to-setup-apt-proxy-on-ubuntu-20-04-lts/
`nano ~/.bashrc` --> add HTTP_PROXY variable
